### ISSUE TITLE
Failure to send

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#1200]
When attempting to "grin wallet send ..." I get the following error most times I try:

`/grin/target/release/grin wallet send -s smallest -d http://grinpool.us:13415 1108.0

The grin wallet command reports this error:
```
Jun 26 00:55:37.341 ERRO Tx not sent: Error { inner: Error { inner: Error { inner: stack backtrace:
   0:     0x56477f108aac - backtrace::backtrace::trace::heaba8652fc04e149
   1:     0x56477f1072c2 - backtrace::capture::Backtrace::new_unresolved::hbb879f7e402f3d3d
   2:     0x56477edfec50 - failure::backtrace::internal::InternalBacktrace::new::h47833e53c17a3dd0
   3:     0x56477edfe8c1 - failure::backtrace::Backtrace::new::h363211e05b2ac1af
   4:     0x56477ed27ff7 - grin_api::client::check_error::h5d292d176019332e
   5:     0x56477ec2ceb2 - grin_api::client::post::hf05c50b8f181ed6b
   6:     0x56477ec3b44e - grin_wallet::client::post_tx::h2c679928645cbfbf
   7:     0x56477ea9067a - <grin_wallet::libwallet::api::APIOwner<'a, W, K>>::issue_send_tx::h58c6a8392a222090
   8:     0x56477eb011e3 - grin_wallet::libwallet::controller::owner_single_use::h5dfe4309ad24d2aa
   9:     0x56477ea6b35a - grin::main::ha68c1781dbb90b3f
  10:     0x56477ea9a9f2 - std::rt::lang_start::{{closure}}::hd33931ef75882803
  11:     0x56477f1c24a7 - std::rt::lang_start_internal::{{closure}}::h30a15dfbaf2db741
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::h84e823ef113bafaa
                        at libstd/panicking.rs:306
  12:     0x56477f1d5cde - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  13:     0x56477f1bef55 - std::panicking::try::h29c76d75c597e452
                        at libstd/panicking.rs:285
                         - std::panic::catch_unwind::h33ca23d1ecc573a8
                        at libstd/panic.rs:361
                         - std::rt::lang_start_internal::h26bd2a105967b459
                        at libstd/rt.rs:58
  14:     0x56477ea6d923 - main
  15:     0x7f91e0a211c0 - __libc_start_main
  16:     0x56477ea26a69 - _start
  17:                0x0 - <unknown>

Bad arguments: Argument error:  }

Node API error }
```

The grin server logs contains this error:
```
Jun 26 01:05:28.527 DEBG Building input (spending regular output): 20305000000, 5234e7b56a52910aa8fc
Jun 26 01:05:28.528 DEBG Building input (spending regular output): 22983000000, 5945d8e7b136221f7553
Jun 26 01:05:28.529 DEBG Building input (spending regular output): 29991000000, b909157d027f642c024a
Jun 26 01:05:28.529 DEBG Building input (spending regular output): 29991000000, 09c57290711581e7876c
Jun 26 01:05:28.529 DEBG Building input (spending regular output): 29991000000, e56e0e7842f1419ff225
Jun 26 01:05:28.529 DEBG Building input (spending regular output): 29991000000, 1cd05635232c40b064b6
Jun 26 01:05:28.530 DEBG Building input (spending coinbase): 60000000000, 15771016b82cbd77ad49
Jun 26 01:05:28.530 DEBG Building input (spending coinbase): 60000000000, a1e0511f4b72c7b944ee
Jun 26 01:05:28.530 DEBG Building input (spending coinbase): 60000000000, 394e1c438bf32bd8d894
Jun 26 01:05:28.530 DEBG Building input (spending coinbase): 60000000000, c31c9ffe248a0f46ac66
Jun 26 01:05:28.530 DEBG Building input (spending coinbase): 60000000000, cc0cf44d8e5ac19239c5
Jun 26 01:05:28.530 DEBG Building input (spending coinbase): 60000000000, ab1beb3f51c5833eaecd
Jun 26 01:05:28.530 DEBG Building input (spending coinbase): 60000000000, 362742773c2244aa1353
Jun 26 01:05:28.530 DEBG Building input (spending coinbase): 60000000000, ffd84a66134ceeac4052
Jun 26 01:05:28.531 DEBG Building input (spending coinbase): 60000000000, 81d7aad18f2042bac104
Jun 26 01:05:28.531 DEBG Building input (spending coinbase): 60000000000, 36d2f83116e63945bb9f
Jun 26 01:05:28.531 DEBG Building input (spending coinbase): 60000000000, e085d8b038c49395da4f
Jun 26 01:05:28.531 DEBG Building input (spending coinbase): 60000000000, 3a330b2d30b695657787
Jun 26 01:05:28.532 DEBG Building input (spending coinbase): 60000000000, dbff046c429b1e092b17
Jun 26 01:05:28.532 DEBG Building input (spending coinbase): 60000000000, 8b68414cf98f7bf36218
Jun 26 01:05:28.532 DEBG Building input (spending coinbase): 60000000000, ea136238940518c1b464
Jun 26 01:05:28.532 DEBG Building input (spending coinbase): 60000000000, ac8c5125f7ffcd745a0d
Jun 26 01:05:28.532 DEBG Building input (spending coinbase): 60000000000, 7a53e49c859bd777394b
Jun 26 01:05:28.533 INFO Acquiring wallet lock ...
Jun 26 01:05:28.818 INFO ... released wallet lock
Jun 26 01:05:29.210 DEBG Building an output: 15249000000, 41ab7549df7b5e398e33
Jun 26 01:05:29.307 DEBG Posting transaction slate to http://grin:13415/v1/wallet/foreign/receive_tx
Jun 26 01:05:29.315 DEBG Using wallet seed file at: ./wallet.seed
Jun 26 01:05:29.338 INFO Acquiring wallet lock ...
Jun 26 01:05:29.691 INFO ... released wallet lock
Jun 26 01:05:29.693 DEBG Building an output: 1168000000000, 396470ce87f493dfcb84
Jun 26 01:05:29.926 INFO Acquiring wallet lock ...
Jun 26 01:05:30.305 INFO ... released wallet lock
Jun 26 01:05:30.346 DEBG Validating final transaction
Jun 26 01:05:30.369 INFO Pushing transaction with 23 inputs and 2 outputs to pool.
Jun 26 01:05:30.369 DEBG pool: add_to_pool: 019e8fdf, kernels - 1, stem? true
Jun 26 01:05:30.383 DEBG error - ImmatureCoinbase
Jun 26 01:05:30.399 ERRO Tx not sent: Error { inner: Error { inner: Error { inner: stack backtrace:
   0:     0x56472524caac - backtrace::backtrace::trace::heaba8652fc04e149
   1:     0x56472524b2c2 - backtrace::capture::Backtrace::new_unresolved::hbb879f7e402f3d3d
   2:     0x564724f42c50 - failure::backtrace::internal::InternalBacktrace::new::h47833e53c17a3dd0
   3:     0x564724f428c1 - failure::backtrace::Backtrace::new::h363211e05b2ac1af
   4:     0x564724e6bff7 - grin_api::client::check_error::h5d292d176019332e
   5:     0x564724d70eb2 - grin_api::client::post::hf05c50b8f181ed6b
   6:     0x564724d7f44e - grin_wallet::client::post_tx::h2c679928645cbfbf
   7:     0x564724bd467a - <grin_wallet::libwallet::api::APIOwner<'a, W, K>>::issue_send_tx::h58c6a8392a222090
   8:     0x564724c451e3 - grin_wallet::libwallet::controller::owner_single_use::h5dfe4309ad24d2aa
   9:     0x564724baf35a - grin::main::ha68c1781dbb90b3f
  10:     0x564724bde9f2 - std::rt::lang_start::{{closure}}::hd33931ef75882803
  11:     0x5647253064a7 - std::rt::lang_start_internal::{{closure}}::h30a15dfbaf2db741
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::h84e823ef113bafaa
                        at libstd/panicking.rs:306
  12:     0x564725319cde - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  13:     0x564725302f55 - std::panicking::try::h29c76d75c597e452
                        at libstd/panicking.rs:285
                         - std::panic::catch_unwind::h33ca23d1ecc573a8
                        at libstd/panic.rs:361
                         - std::rt::lang_start_internal::h26bd2a105967b459
                        at libstd/rt.rs:58
  14:     0x564724bb1923 - main
  15:     0x7f91fa9491c0 - __libc_start_main
  16:     0x564724b6aa69 - _start
  17:                0x0 - <unknown>

Bad arguments: Argument error:  }

Node API error }
```

The wallet looks like this:
```
____ Wallet Summary Info as of 121383 ____

 Total                            | 51392.712000000 
 Awaiting Confirmation            | 20625.422000000 
 Immature Coinbase                | 5580.030000000 
 Currently Spendable              | 25187.260000000 
 ---------                        | --------- 
 (Locked by previous transaction) | 0.000000000 
```

**Comment by bladedoyle** [comment]
Another problem is that even when the send fails, the grin wallet send command edits with ok (0) status code.

root@grin-847b9cf567-x26pq:/server# grin wallet send -d http://grinpool.us:13415 0.1
Jun 26 20:33:37.638 ERRO Tx not sent: Error { inner: Error { inner: Error { inner: 

Bad arguments: Argument error:  }

Node API error }

Node API error }
root@grin-847b9cf567-x26pq:/server# **echo $?
0**

**Comment by yeastplume** [comment]
I believe I've just fixed this on testnet 3.. can you try it from that branch?

**Comment by bladedoyle** [comment]
@yeastplume 

Thanks.  The sending failures seem resolved.

But when there is a legitimate issue (in my example I try to send the the wrong port) I still get a "0" exit status from the command.

```
root@makepayouts-1531357500-v2mc9:/wallet# /usr/local/bin/grin wallet send -s smallest -d http://192.168.2.225:1 123.45
Jul 12 01:06:17.821 ERRO Tx not sent: Error { inner: Error { inner: Io(Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" })

Internal error: Error during request }

Client Callback Error: Getting chain height from node }
Jul 12 01:06:17.821 ERRO Backtrace: 
root@makepayouts-1531357500-v2mc9:/wallet# echo $?
0
```
