### ISSUE TITLE
thread 'main' panicked at 'no root, invalid tree'

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1620]
`q` to exit Grin when it's validating the txhashset, then can't start anymore:

```
Oct 01 16:04:41.914 INFO This is Grin version 0.3.0 (git 0.0.0-pre.0.3.0-13-g6ad54b9), built for x86_64-apple-darwin by rustc 1.29.0 (aa3ca1994 2018-09-11).
Oct 01 16:04:41.914 DEBG Built with profile "release", features "" on Mon, 01 Oct 2018 07:49:00 GMT.
Oct 01 16:04:41.914 WARN Starting GRIN in UI mode...
Oct 01 16:04:41.915 INFO Starting server, genesis block: 006642e0
Oct 01 16:04:42.085 DEBG prune_list: bitmap 18570 pos (23198 bytes), pruned_cache 64932 pos (27564 bytes), shift_cache 18570, leaf_shift_cache 18570
Oct 01 16:04:42.256 DEBG prune_list: bitmap 18570 pos (23198 bytes), pruned_cache 64932 pos (27564 bytes), shift_cache 18570, leaf_shift_cache 18570
Oct 01 16:04:42.388 ERRO
thread 'main' panicked at 'no root, invalid tree': libcore/option.rs:989stack backtrace:
   0:        0x105ebea1e - backtrace::backtrace::trace::h202012485f8b264e
   1:        0x105ebf79c - <backtrace::capture::Backtrace as core::default::Default>::default::h88ea78bbe20947fe
   2:        0x105ebf81d - backtrace::capture::Backtrace::new::h409b2ab533e65b32
   3:        0x105e4e351 - grin_util::logger::send_panic_to_log::{{closure}}::he8a5401a4a6174c0
   4:        0x105fe15a8 - std::panicking::rust_panic_with_hook::h28749c6c929f49fc
   5:        0x105fe10fc - std::panicking::continue_panic_fmt::h2b83096170ce8c01
   6:        0x105fe0fe8 - _rust_begin_unwind
   7:        0x106023c11 - core::panicking::panic_fmt::h014200104cad7730
   8:        0x106023d78 - core::option::expect_failed::hac7b2b644a466466
   9:        0x105d874fd - <grin_core::core::pmmr::pmmr::PMMR<'a, T, B>>::root::h3eb36713e0ad170f
  10:        0x105d37c3d - grin_chain::txhashset::txhashset::Extension::validate_roots::hb9864e0e3744ed1b
  11:        0x105d2fb6f - grin_chain::txhashset::txhashset::extending::h7b61076986fba04f
  12:        0x105d6d38c - grin_chain::chain::Chain::init::hc2b61fcc98f125b2
  13:        0x105a43387 - grin_servers::grin::server::Server::new::h7d36c8da0c1170bf
  14:        0x1059812ba - grin_servers::grin::server::Server::start::hc390b720136e4000
  15:        0x105932ee8 - grin::cmd::server::start_server::he0a351716bec0dd7
  16:        0x105933694 - grin::cmd::server::server_command::h4e4711767dd5f892
  17:        0x10598e3e7 - grin::main::hc1cd50fa887acb30
  18:        0x105915e55 - std::rt::lang_start::{{closure}}::h2ae370964403f437
  19:        0x105fe0f67 - std::panicking::try::do_call::hdceefc76f62a2c0e
  20:        0x105fecf6e - ___rust_maybe_catch_panic
  21:        0x105fcfd2c - std::rt::lang_start_internal::he24cbd8cd122f539
  22:        0x10598f94b - _main

```

**Comment by garyyu** [comment]
debug version:

```
thread 'main' panicked at 'no root, invalid tree': libcore/option.rs:989stack backtrace:
   0:        0x10f47f844 - backtrace::backtrace::trace::h82eb823bdd666e6f
                        at /Users/garyyu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:        0x10f47a78c - backtrace::capture::Backtrace::new_unresolved::h1572ddbcdcb8a4c9
                        at /Users/garyyu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:        0x10f47a6ee - backtrace::capture::Backtrace::new::hd858d1b781edfd7f
                        at /Users/garyyu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:63
   3:        0x10f35d7f9 - grin_util::logger::send_panic_to_log::{{closure}}::h94f1d7697716acb3
                        at util/src/logger.rs:121
   4:        0x10f91e738 - std::panicking::rust_panic_with_hook::h28749c6c929f49fc
                        at libstd/panicking.rs:479
   5:        0x10f91e28c - std::panicking::continue_panic_fmt::h2b83096170ce8c01
                        at libstd/panicking.rs:390
   6:        0x10f91e178 - _rust_begin_unwind
                        at libstd/panicking.rs:325
   7:        0x10f961071 - core::panicking::panic_fmt::h014200104cad7730
                        at libcore/panicking.rs:77
   8:        0x10f9611d8 - core::option::expect_failed::hac7b2b644a466466
                        at libcore/option.rs:989
   9:        0x10f06ca1c - <core::option::Option<T>>::expect::h0de4e74b43b1fa19
                        at /Users/travis/build/rust-lang/rust/src/libcore/option.rs:312
  10:        0x10f03f395 - <grin_core::core::pmmr::pmmr::PMMR<'a, T, B>>::root::h5010a35b703f7b84
                        at /Users/garyyu/develop/projects/github.com/mimblewimble/grin/core/src/core/pmmr/pmmr.rs:135
  11:        0x10f00e4a0 - grin_chain::txhashset::txhashset::Extension::roots::h7af0e57ac0224716
                        at chain/src/txhashset/txhashset.rs:715
  12:        0x10f00e593 - grin_chain::txhashset::txhashset::Extension::validate_roots::hc98c7aa5f5967c08
                        at chain/src/txhashset/txhashset.rs:729
  13:        0x10f0282c2 - grin_chain::chain::setup_head::{{closure}}::hfff90d7a45cd1ca6
                        at chain/src/chain.rs:1009
  14:        0x10f033a30 - grin_chain::txhashset::txhashset::extending::h4d6ba02a5a78d94b
                        at chain/src/txhashset/txhashset.rs:357
  15:        0x10f0521aa - grin_chain::chain::setup_head::h95bb4a464da8349d
                        at chain/src/chain.rs:1007
  16:        0x10f042fb6 - grin_chain::chain::Chain::init::h147cf6eb01a34bb0
                        at chain/src/chain.rs:184
  17:        0x10e88dcc3 - grin_servers::grin::server::Server::new::h6543786fb515131d
                        at servers/src/grin/server.rs:160
  18:        0x10e6f1497 - grin_servers::grin::server::Server::start::h23f9dd9843fd6483
                        at /Users/garyyu/develop/projects/github.com/mimblewimble/grin/servers/src/grin/server.rs:75
  19:        0x10e60a69b - grin::cmd::server::start_server_tui::h67d3e86c3d9b3375
                        at src/bin/cmd/server.rs:51
  20:        0x10e60a2c4 - grin::cmd::server::start_server::h7138663cacda44b0
                        at src/bin/cmd/server.rs:36
  21:        0x10e60ae74 - grin::cmd::server::server_command::h05128a01b7aeee1c
                        at src/bin/cmd/server.rs:187
  22:        0x10e56c8b3 - grin::main::h58f9cc669d75c164
                        at src/bin/grin.rs:421
```

**Comment by antiochp** [comment]
We changed the SIGTERM/SIGKILL handlers recently right? Might this be related?

**Comment by ignopeverell** [comment]
This has likely always been there, the server stop method has no delay or cleanup if it occurs while the txhashset is being processed. It'd still be good to have logs for _exactly when_ the server was stopped, but given that it impacts the MMR root I'm guessing it has to do with indexes recreation or leafset copying (although I think that would fix itself).

The easiest fix would be to save a dummy file at the end of a txhashset validation and remove the whole thing to resync if we don't find it.

**Comment by antiochp** [comment]
Yeah agreed. Something changed recently that just makes this more visible and/or happens more regularly.
It could be the `batch` changes or the way we changed how things get locked (aka deadlocking...) as well.

**Comment by garyyu** [comment]
Closed not reproduced in latest version.

**Comment by antiochp** [comment]
Suspect this was fixed as part of cleaning up our caching code - we had scenarios where the cache was not invalidated correctly, potentially resulting in stale reads.

**Comment by kargakis** [comment]
Still seeing this, or at least a similar error in v1.1.0-beta1
```
20190414 08:44:39.099 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Warn, min. level: Debug
20190414 08:44:39.099 INFO grin - Using configuration file at /home/mkargaki/.grin/floo/grin-server.toml
20190414 08:44:39.099 INFO grin - This is Grin version 1.1.0-beta.1 (git 1.1.0-beta.1), built for x86_64-unknown-linux-gnu by rustc 1.33.0 (2aa4c46cf 2019-02-28).
20190414 08:44:39.099 DEBUG grin - Built with profile "release", features "".
20190414 08:44:39.099 WARN grin::cmd::server - Starting GRIN in UI mode...
20190414 08:44:39.099 INFO grin_servers::grin::server - Starting server, genesis block: edc758c1370d
20190414 08:44:39.100 DEBUG grin_store::lmdb - DB Mapsize for /home/mkargaki/.grin/floo/chain_data/lmdb is 549755813888
20190414 08:44:39.104 DEBUG grin_chain::txhashset::txhashset - About to rebuild header extension from edc758c1370d to 02be4afe6199.
20190414 08:44:42.036 DEBUG grin_chain::txhashset::txhashset - Truncating header extension.
20190414 08:44:42.036 DEBUG grin_chain::txhashset::txhashset - Re-applying 113676 headers to extension, from 026ea6242f72 to 02be4afe6199.
20190414 08:44:45.758 DEBUG grin_chain::txhashset::txhashset - Rewind to header 02be4afe6199 at 113676
20190414 08:44:45.758 DEBUG grin_chain::txhashset::txhashset - txhashset: rewind_to_pos: header 227345, output 345858, kernel 277313
20190414 08:44:45.758 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20190414 08:44:45.758 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20190414 08:44:45.759 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20190414 08:44:45.759 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20190414 08:44:45.759 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20190414 08:44:45.759 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20190414 08:44:45.759 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20190414 08:44:45.759 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20190414 08:44:45.813 ERROR grin_util::logger - 
thread 'main' panicked at 'no root, invalid tree': src/libcore/option.rs:1038stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}::hf7ab53c8e0b02861 (0x558557f180f0)
   1: std::panicking::rust_panic_with_hook::h744417edfe714d72 (0x55855803dbe9)
             at src/libstd/panicking.rs:482
   2: std::panicking::continue_panic_fmt::h3557b3c3fa21b47b (0x55855803d691)
             at src/libstd/panicking.rs:385
   3: rust_begin_unwind (0x55855803d575)
             at src/libstd/panicking.rs:312
   4: core::panicking::panic_fmt::h74ee8034b317ceed (0x5585580583bc)
             at src/libcore/panicking.rs:85
   5: core::option::expect_failed::hbc312d76c0b547f0 (0x558558058432)
             at src/libcore/option.rs:1038
   6: <grin_core::core::pmmr::pmmr::PMMR<'a, T, B>>::root::h2439dc6a2d01232b (0x558557e088e5)
   7: grin_chain::txhashset::txhashset::Extension::validate_roots::h64e0bc2eebd093a2 (0x558557dc72cc)
   8: grin_chain::txhashset::txhashset::extending::hc98181ff9d4ab212 (0x558557dbb17f)
   9: grin_chain::chain::Chain::init::hdcbe27fe3bf467d1 (0x558557dd1c57)
  10: grin_servers::grin::server::Server::new::he0221117520483fe (0x5585579e15ea)
  11: grin_servers::grin::server::Server::start::h5eae47819c31e98f (0x5585578df007)
  12: grin::cmd::server::start_server::h60daae9653a1649c (0x5585578a3b7d)
  13: grin::cmd::server::server_command::h9595d94d31f59738 (0x5585578a4662)
  14: grin::real_main::h54160841d21d6642 (0x5585578e7c74)
  15: grin::main::h726b46fb899da6db (0x5585578e6b55)
  16: std::rt::lang_start::{{closure}}::h25c488057ca7de7b (0x5585578aeed2)
  17: std::rt::lang_start_internal::{{closure}}::h8ad4264c6b68797c (0x55855803d512)
             at src/libstd/rt.rs:49
      std::panicking::try::do_call::h7a0381557c6c2cee
             at src/libstd/panicking.rs:297
  18: __rust_maybe_catch_panic (0x558558043fa9)
             at src/libpanic_unwind/lib.rs:92
  19: std::panicking::try::h72cb0fef6e9c0ab1 (0x55855803e065)
             at src/libstd/panicking.rs:276
      std::panic::catch_unwind::hbff071ae76e6f224
             at src/libstd/panic.rs:388
      std::rt::lang_start_internal::he0d8d06abc6f912f
             at src/libstd/rt.rs:48
  20: main (0x5585578e81e1)
  21: __libc_start_main (0x7f027032c11a)
  22: <unknown> (0x55855788c200)
  23: <unknown> (0x0)
```
A couple of notes:
- this was on floonet
- I had restarted my floonet node yesterday after a while to test v1.1.0-beta1 and it was working fine (don't think I let it sync all the way to latest block though)
- mainnet node runs fine on the same version
- running both nodes side by side on the same machine
- cannot start the floonet node anymore
- I can email a tar with the chain data to whoever wants to debug further

**Comment by kargakis** [comment]
debug log:
```
thread 'main' panicked at 'no root, invalid tree': src/libcore/option.rs:1038stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}::h4d1be965e4d42cc4 (0x557f5e667d7b)
             at util/src/logger.rs:240
   1: std::panicking::rust_panic_with_hook::hfd44f6005c88b9cd (0x557f5eb33b49)
   2: std::panicking::continue_panic_fmt::h49294ee7e45fe937 (0x557f5eb33601)
   3: rust_begin_unwind (0x557f5eb334e5)
   4: core::panicking::panic_fmt::h50061a1f3a2a7f40 (0x557f5eb44dac)
   5: core::option::expect_failed::ha7629b64ee08267d (0x557f5eb44e22)
   6: <core::option::Option<T>>::expect::h8fb29199247764e4 (0x557f5e215ba6)
             at /builddir/build/BUILD/rustc-1.33.0-src/src/libcore/option.rs:312
   7: <grin_core::core::pmmr::pmmr::PMMR<'a, T, B>>::root::h466edd982bd33f32 (0x557f5e2db009)
             at /home/mkargaki/projects/grin/core/src/core/pmmr/pmmr.rs:144
   8: grin_chain::txhashset::txhashset::Extension::roots::h81c694c3458e92a3 (0x557f5e23afaa)
             at chain/src/txhashset/txhashset.rs:1093
   9: grin_chain::txhashset::txhashset::Extension::validate_roots::hfdce72456b25ad9d (0x557f5e23b102)
             at chain/src/txhashset/txhashset.rs:1121
  10: grin_chain::chain::setup_head::{{closure}}::h336d1a28aa77a124 (0x557f5e2abe1a)
             at chain/src/chain.rs:1324
  11: grin_chain::txhashset::txhashset::extending::h4491120da278e77e (0x557f5e2997ba)
             at chain/src/txhashset/txhashset.rs:439
  12: grin_chain::chain::setup_head::hd00f84ab6d70e25d (0x557f5e2cd451)
             at chain/src/chain.rs:1322
  13: grin_chain::chain::Chain::init::h8dcd9a99b08144c4 (0x557f5e2b8d18)
             at chain/src/chain.rs:185
  14: grin_servers::grin::server::Server::new::hee84b6e5e8ca08db (0x557f5d8b86c0)
             at servers/src/grin/server.rs:181
  15: grin_servers::grin::server::Server::start::h50dfa6fccd0f55e4 (0x557f5d4914aa)
             at /home/mkargaki/projects/grin/servers/src/grin/server.rs:83
  16: grin::cmd::server::start_server_tui::h5c31050d0e9e98dd (0x557f5d4be695)
             at src/bin/cmd/server.rs:48
  17: grin::cmd::server::start_server::h135158a038f4b9dc (0x557f5d4be2b6)
             at src/bin/cmd/server.rs:33
  18: grin::cmd::server::server_command::h5dd1ce1ff68ccb35 (0x557f5d4bef74)
             at src/bin/cmd/server.rs:145
  19: grin::real_main::h935e376770d64802 (0x557f5d4b89f2)
             at src/bin/grin.rs:158
  20: grin::main::h3e5a47108688770f (0x557f5d4b7a95)
             at src/bin/grin.rs:67
  21: std::rt::lang_start::{{closure}}::hbfe76648c32774f3 (0x557f5d56d11f)
             at /builddir/build/BUILD/rustc-1.33.0-src/src/libstd/rt.rs:64
  22: std::panicking::try::do_call::ha2b2f50005aee932 (0x557f5eb33482)
  23: __rust_maybe_catch_panic (0x557f5eb368a9)
  24: std::rt::lang_start_internal::h5b4ed6f311caad20 (0x557f5eb2902f)
  25: std::rt::lang_start::h2f1f809f1b014057 (0x557f5d56d0f8)
             at /builddir/build/BUILD/rustc-1.33.0-src/src/libstd/rt.rs:64
  26: main (0x557f5d4b8f1c)
  27: __libc_start_main (0x7fee980b311a)
  28: _start (0x557f5d43ed99)
  29: <unknown> (0x0)
```

**Comment by antiochp** [comment]
@kargakis There must still be some kind of race condition during `ctrl-c` (or `q`) during a sync.

We're not cleaning something up and/or the txhashset and/or the db is getting left in some inconsistent state. And we are not correctly rewinding to resolve this on next startup.
