### ISSUE TITLE
illegal instruction (core dumped) - with 0.5.2

### ISSUE THREAD

**Issue by aleqx** [mimblewimble/grin#2383]
This is still happening. Clean system, Ubuntu 16.04 x64, dual Xeon. Launching it for the first time brought up the text gui, worked for a minute, connected to a few peers, then crashed. Tryi9ng to launch it again and I get:

```
# ./grin --floonet
Illegal instruction (core dumped)
```

**Comment by Gigabyted** [comment]
Have  the same issue here as well

**Comment by BravoIndia** [comment]
Similar post: https://www.grin-forum.org/t/illegal-instruction-core-dumped/2058
Did you get this from the release?

No direct solution offered, but deleting you ~/.grin directory and building from source instead of the release worked for me and another user.

**Comment by aleqx** [comment]
This is from current master

**Comment by mqhack** [comment]
Same here, the server doesn't run. 
Log: https://gist.github.com/mqhack/c8f8660446cf670a07a8c0cf1389051f

**Comment by mqhack** [comment]
quick update, it's fixed now at master after pulling correct genesis block

**Comment by doodle10** [comment]
still having this problem on mainet version compiled from master. same thing if I download the release that is already compiled

**Comment by ignopeverell** [comment]
This is too generic of an error for us to debug, and I'm guessing several people in this thread had different versions of it (like mainnet before genesis was created). Feel free to reopen something more specific (check logs) if it's still happening.
