### ISSUE TITLE
Synced node stops making progress

### ISSUE THREAD

**Issue by hashmap** [mimblewimble/grin#2994]
After running a few days a node (commit ea1d14ddb095485e487b65c9555339cb198dca70) stuck at some point with error:
```
20190821 17:08:07.836 DEBUG grin_chain::txhashset::txhashset - txhashset: rewind_to_pos: header 613517, output 3485577, kernel 1846143
20190821 17:08:07.837 DEBUG grin_chain::txhashset::txhashset - Error returned, discarding txhashset extension: TxHashSetErr: missing left sibling in tree, should not have been pruned
 Cause: Unknown
 Backtrace:
20190821 17:08:07.837 INFO grin_chain::chain - Rejected block 000000c81f28 at 306764: Error { inner:

TxHashSetErr: missing left sibling in tree, should not have been pruned }
20190821 17:08:07.837 DEBUG grin_servers::common::adapters - process_block: block 000000c81f28 refused by chain: Other Error: Error { inner:

TxHashSetErr: missing left sibling in tree, should not have been pruned }
20190821 17:08:07.837 DEBUG grin_servers::grin::sync::body_sync - block_sync: 306763/312628 requesting blocks [000000c81f28] from 3 peers
```
After restart it was able to continue sync, so stored data was not corrupted

**Comment by antiochp** [comment]
Hi @jyap808 can you checkout latest `master` and see if your node can unstick itself?

We _think_ this is resolved with https://github.com/mimblewimble/grin/pull/3005

Thanks!

**Comment by jyap808** [comment]
I ran a full sync with Grin HEAD and it worked fine, no issues. Patch LGTM

**Comment by jyap808** [comment]
Looks like there's still an issue @antiochp. Node is stuck again.

```
20190901 00:51:06.258 INFO grin_chain::chain - Rejected block 000000dbce95 at 327936: Error { inner: 

Invalid Root }
20190901 00:51:17.311 INFO grin_chain::chain - Rejected block 000000dbce95 at 327936: Error { inner: 

Invalid Root }
20190901 00:51:28.413 INFO grin_chain::chain - Rejected block 000000dbce95 at 327936: Error { inner: 

Invalid Root }
20190901 00:51:39.478 INFO grin_chain::chain - Rejected block 000000dbce95 at 327936: Error { inner: 

Invalid Root }
20190901 00:51:50.527 INFO grin_chain::chain - Rejected block 000000dbce95 at 327936: Error { inner: 

Invalid Root }
20190901 00:52:01.679 INFO grin_chain::chain - Rejected block 000000dbce95 at 327936: Error { inner: 

Invalid Root }
20190901 00:52:12.739 INFO grin_chain::chain - Rejected block 000000dbce95 at 327936: Error { inner: 

Invalid Root }
20190901 00:52:23.767 INFO grin_chain::chain - Rejected block 000000dbce95 at 327936: Error { inner: 

Invalid Root }
20190901 00:52:34.820 INFO grin_chain::chain - Rejected block 000000dbce95 at 327936: Error { inner: 

Invalid Root }
20190901 00:52:45.906 INFO grin_chain::chain - Rejected block 000000dbce95 at 327936: Error { inner: 

Invalid Root }
```

**Comment by jyap808** [comment]
This can probably be closed. New issue covered in #3030

**Comment by garyyu** [comment]
@jyap808 I think issue 3030 is not the case of this issue which has an obvious error indicator `TxHashSetErr: missing left sibling in tree`.

(and your `Invalid Root` case should already been fixed in latest master branch, perhaps by PR 3017)

(I don't use the # to avoid linking these unrelated issues together)

**Comment by yeastplume** [comment]
Looks like this can likely be closed?

**Comment by quentinlesceller** [comment]
Closing.
