### ISSUE TITLE
Wallet receive fails with panic

### ISSUE THREAD

**Issue by casey** [mimblewimble/grin#329]
My wallet was partially synced, 3000/3600 or so. When I was sent funds, I got the following backtrace:

https://gist.github.com/casey/dc8972ed2d592904c92425af0bfa74ce

**Comment by sesam** [comment]
@casey Did you actually have the binary build in release, not debug, at first? If so, what would be the advantage? Only reason I can think of is to use less memory if running on a shared VM, but would RAM usage really be enough to warrant not staying in debug mode all through testnet1.

I think the current release needs a restart to be able to orphan even a single locally mined block, to follow the longer chain.

**Comment by ignopeverell** [comment]
@sesam "I think the current release needs a restart to be able to orphan even a single locally mined block"

If that's the case I'd love an issue with some logs showing this. In theory that should be working, unless the block in the winning side was missed by the local node due to bad relay for example.

**Comment by ignopeverell** [comment]
The logs indicate that the transaction was properly built but a server error occurred when the wallet sent it to the server for broadcast. Would you still have your server logs around the time that error occurred?

**Comment by casey** [comment]
Yup, I still have the logs. I added what appears to be the relevant part to the gist:

https://gist.github.com/casey/dc8972ed2d592904c92425af0bfa74ce#file-server-log

**Comment by AsrielBelacqua** [comment]
Not sure if this is any help, but the panic in this one seems to be the same as in #307

**Comment by ignopeverell** [comment]
Closing this in preparation for Testnet2. Likely fixed or very different now.
