### ISSUE TITLE
My node has forked because of an "AlreadySpent" error

### ISSUE THREAD

**Issue by mably** [mimblewimble/grin#505]
My node forked on his own chain and has been followed there by a few peers because it refused the block 21455 on an "AlreadySpent" error 👍 
```
Dec 17 16:37:54.882 INFO Rejected block 9cbb3c80 at 21455: AlreadySpent
Dec 17 16:37:54.883 DEBG Block 9cbb3c80 refused by chain: AlreadySpent
```
This block seems to be considered as valid on the main chain.

My node is up-to-date to yesterday's commits.

Here is the log since my node's last start:

https://pastebin.com/201QrQtC

**Comment by mably** [comment]
I have kept a backup of my .grin directory in case somebody needs it to investigate.

**Comment by mably** [comment]
Don't know if it could be related to a previous miner thread crash: https://pastebin.com/P41Wfjvx

**Comment by ignopeverell** [comment]
@mably could you gzip and attach your `.grin/sumtree` directory from that point in time? Should be a lot smaller thatn the whole thing. Also I'm assuming that node had been resynced since 54b2be7 was fixed, correct?

**Comment by mably** [comment]
Here it is: [sumtrees.zip](https://github.com/mimblewimble/grin/files/1565878/sumtrees.zip)

**Comment by ignopeverell** [comment]
Would you have the logs prior to what you posted, when the first block at 21455 arrived? You should have something like `at 21455 is valid, save and apppend` in your logs

**Comment by quentinlesceller** [comment]
Encountered the same issue at block 21708
```
Dec 19 16:59:12.972 INFO Rejected block 9abfa907 at 21708: AlreadySpent(Commitment(08c68d97b7bfb2663b34fbe8d67bd5af2a104efdd04b6e942bf7df2b5191c5a81b))
Dec 19 16:59:33.607 INFO Client 192.241.168.77:13414 connection lost: Timeout
Dec 19 16:59:37.314 INFO sync: no peers available, disabling sync
Dec 19 16:59:46.990 INFO (Server ID: Port 13414) Found valid proof of work, adding block e483a808.
```
After that my node started mining on its own chain.
Node is running version after commit [3dc44bc](https://github.com/mimblewimble/grin/commit/3dc44bc504af4e74f3774ae252d4a56b0a9c1473).
Restarting the node did not help.
Here is my log: [pastebin](https://pastebin.com/cjRR2yeS).

**Comment by ignopeverell** [comment]
Should be fixed by 273ea26

**Comment by quentinlesceller** [comment]
After deleting my .grin directory and started syncing again, I still have this error on another block.
``` Rejected block f697a877 at 4689: AlreadySpent(Commitment(085c965708c6519a4d80db919cf2802660c01179ec33eb675eb84b1f7aa09fda0e))```
I'm running testate version with commit https://github.com/mimblewimble/grin/commit/273ea26e7c70fff1069b348b27f133e3189e0ada
Log can be found here: [pastebin](https://pastebin.com/v4CUk8KS).
