### ISSUE TITLE
starting mining node up with no running wallet is no longer working (regression?)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#768]
```
Mar 13 16:01:30.642 ERRO Failed to get coinbase from http://127.0.0.1:13415/v1/receive/coinbase. Run grin wallet listen
Mar 13 16:01:30.643 ERRO Successfully received coinbase from http://127.0.0.1:13415/v1/receive/coinbase
thread 'miner' panicked at 'cannot recursively call into `Core`', src/libcore/option.rs:891:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

We used to loop and wait for the wallet to start (polling for it with a backoff).

Not had time to investigate further so opening issue so we don't forget about this.

**Comment by yeastplume** [comment]
@ignopeverell made a sneaky commit here to do with automatically running wallet listeners if desired https://github.com/mimblewimble/grin/commit/a8fcc37a364059248a87198162dc3563e79f547b Will have a look into it now

**Comment by yeastplume** [comment]
Probably fixed by https://github.com/mimblewimble/grin/pull/774 along with a few other things, but I never saw that particular panic at any point. Can you check again once I've merged that one?

**Comment by ignopeverell** [comment]
Yeah, sorry for the sneakiness, bad case of PR laziness. Still not sure what would have caused the above though, the listener only panics without a seed, and should have asked for one.

**Comment by antiochp** [comment]
I can take another look. Definitely had a seed file in place - I just forgot to start the wallet listener first.
